### Products

GET http://localhost:8080/products

### Add item to watch list
PUT http://localhost:8080/users/1/watchlist HTTP/1.1
content-type: application/json

{
  "product": 2
}

### Remove item from watch list
DELETE http://localhost:8080/users/1/watchlist/2

### Users

### Create user
POST http://localhost:8080/users HTTP/1.1

### Create webhook user
POST http://localhost:8080/webhooks/users
Content-Type: application/json

{
  "hook": "http://54.38.214.68:8080/price-hook"
}

### Get user
GET http://localhost:8080/users/1 HTTP/1.1

### Get non existent user
GET http://localhost:8080/users/100 HTTP/1.1


### Create webhook
POST http://localhost:8080/webhooks HTTP/1.3
content-type: application/json

{
  "hook": "http://54.38.214.68:8080/price-hook"
}


### Register products (search)
POST http://localhost:8080/products/search
Content-Type: application/json

{
  "product": "7800x3d"
}

### Register product by url (globaldata)
POST http://localhost:8080/webhooks/products
Content-Type: application/json

{
  "user": 1,
  "url": "https://www.globaldata.pt/processador-amd-ryzen-7-7800x3d-8-core-42ghz-50ghz-104mb-am5-100-100000910wof",
  "hook": "http://54.38.214.68:8080/price-hook"
}

### Register product by url (pcdiga)
POST http://localhost:8080/webhooks/products
Content-Type: application/json

{
  "user": 1,
  "url": "https://www.pcdiga.pt/processador-amd-ryzen-7-7800x3d-8-core-42ghz-50ghz-104mb-am5-100-100000910wof",
  "hook": "http://54.38.214.68:8080/price-hook"
}